<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MateriasSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('materias')->insert([
            [
                'codigo' => 'MAT001',
                'nombre' => 'Matemáticas',
                'descripcion' => 'Fundamentos de álgebra, geometría y aritmética.',
                'creditos' => 4,
                'horas_semanales' => 4,
                'grado' => '10°',
                'docente' => 'Prof. García',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'ESP001',
                'nombre' => 'Español',
                'descripcion' => 'Comprensión lectora y producción de textos.',
                'creditos' => 3,
                'horas_semanales' => 3,
                'grado' => '9°',
                'docente' => 'Prof. López',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'ING001',
                'nombre' => 'Inglés',
                'descripcion' => 'Inglés intermedio, énfasis en habilidades comunicativas.',
                'creditos' => 3,
                'horas_semanales' => 3,
                'grado' => '11°',
                'docente' => 'Prof. Martínez',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'CIE001',
                'nombre' => 'Ciencias Naturales',
                'descripcion' => 'Biología y química básica.',
                'creditos' => 4,
                'horas_semanales' => 4,
                'grado' => '10°',
                'docente' => 'Prof. Rodríguez',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'SOC001',
                'nombre' => 'Sociales',
                'descripcion' => 'Historia y geografía general.',
                'creditos' => 3,
                'horas_semanales' => 3,
                'grado' => '9°',
                'docente' => 'Prof. Pérez',
                'estado' => 'Inactivo',
            ],
            [
                'codigo' => 'FIS001',
                'nombre' => 'Física',
                'descripcion' => 'Conceptos básicos de mecánica y energía.',
                'creditos' => 4,
                'horas_semanales' => 4,
                'grado' => '11°',
                'docente' => 'Prof. Ramírez',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'QUI001',
                'nombre' => 'Química',
                'descripcion' => 'Introducción a la química orgánica e inorgánica.',
                'creditos' => 3,
                'horas_semanales' => 3,
                'grado' => '10°',
                'docente' => 'Prof. Suárez',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'INF001',
                'nombre' => 'Informática',
                'descripcion' => 'Herramientas ofimáticas y conceptos básicos de programación.',
                'creditos' => 2,
                'horas_semanales' => 2,
                'grado' => '9°',
                'docente' => 'Prof. Castillo',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'EDU001',
                'nombre' => 'Educación Física',
                'descripcion' => 'Actividades deportivas y cuidado del cuerpo.',
                'creditos' => 2,
                'horas_semanales' => 2,
                'grado' => '8°',
                'docente' => 'Prof. Torres',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'ART001',
                'nombre' => 'Arte',
                'descripcion' => 'Expresión plástica y apreciación artística.',
                'creditos' => 2,
                'horas_semanales' => 2,
                'grado' => '7°',
                'docente' => 'Prof. Herrera',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'MUS001',
                'nombre' => 'Música',
                'descripcion' => 'Fundamentos de teoría musical e interpretación.',
                'creditos' => 2,
                'horas_semanales' => 2,
                'grado' => '6°',
                'docente' => 'Prof. Rojas',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'FIL001',
                'nombre' => 'Filosofía',
                'descripcion' => 'Introducción al pensamiento filosófico.',
                'creditos' => 3,
                'horas_semanales' => 3,
                'grado' => '11°',
                'docente' => 'Prof. Medina',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'ETI001',
                'nombre' => 'Ética',
                'descripcion' => 'Reflexión sobre valores y convivencia.',
                'creditos' => 2,
                'horas_semanales' => 2,
                'grado' => '10°',
                'docente' => 'Prof. Vargas',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'REL001',
                'nombre' => 'Religión',
                'descripcion' => 'Estudio de diferentes tradiciones religiosas.',
                'creditos' => 1,
                'horas_semanales' => 1,
                'grado' => '7°',
                'docente' => 'Prof. Jiménez',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'TEC001',
                'nombre' => 'Tecnología',
                'descripcion' => 'Proyectos tecnológicos y uso responsable de la tecnología.',
                'creditos' => 2,
                'horas_semanales' => 2,
                'grado' => '8°',
                'docente' => 'Prof. Rivera',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'ORI001',
                'nombre' => 'Orientación Escolar',
                'descripcion' => 'Apoyo a la vida académica y personal.',
                'creditos' => 1,
                'horas_semanales' => 1,
                'grado' => '9°',
                'docente' => 'Prof. Delgado',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'BIO001',
                'nombre' => 'Biología',
                'descripcion' => 'Estudio de los seres vivos y sus procesos.',
                'creditos' => 3,
                'horas_semanales' => 3,
                'grado' => '10°',
                'docente' => 'Prof. Castaño',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'GEO001',
                'nombre' => 'Geometría',
                'descripcion' => 'Figuras, ángulos y teoremas básicos.',
                'creditos' => 2,
                'horas_semanales' => 2,
                'grado' => '8°',
                'docente' => 'Prof. León',
                'estado' => 'Inactivo',
            ],
            [
                'codigo' => 'HIS001',
                'nombre' => 'Historia',
                'descripcion' => 'Historia de Colombia y del mundo.',
                'creditos' => 3,
                'horas_semanales' => 3,
                'grado' => '9°',
                'docente' => 'Prof. Rubio',
                'estado' => 'Activo',
            ],
            [
                'codigo' => 'PRO001',
                'nombre' => 'Programación',
                'descripcion' => 'Introducción a la lógica de programación.',
                'creditos' => 3,
                'horas_semanales' => 3,
                'grado' => '11°',
                'docente' => 'Prof. González',
                'estado' => 'Activo',
            ],
        ]);
    }
}
